// Default role templates. Owner can customise per resort via the admin UI
// (gated by RBAC_EDIT). These are seeded on resort creation.

import type { PermissionKey } from "./permissions.js";

export interface RoleTemplate {
  key: string;
  name: string;
  description: string;
  isSystem: boolean;
  permissions: PermissionKey[];
}

export const DEFAULT_ROLES: RoleTemplate[] = [
  {
    key: "OWNER",
    name: "Owner",
    description: "Full access to everything in the resort.",
    isSystem: true,
    permissions: [], // owner gets everything; resolved at runtime
  },
  {
    key: "MANAGER",
    name: "Manager",
    description: "Operational manager. All bookings, rooms, pricing, housekeeping, reports, settings.",
    isSystem: true,
    permissions: [
      "BOOKING_VIEW",
      "BOOKING_CREATE",
      "BOOKING_CREATE_WALKIN",
      "BOOKING_CREATE_PHONE",
      "BOOKING_MODIFY",
      "BOOKING_CANCEL",
      "BOOKING_CONFIRM",
      "BOOKING_CHECKIN",
      "BOOKING_CHECKOUT",
      "BOOKING_ASSIGN_ROOM",
      "BOOKING_MOVE_ROOM",
      "BOOKING_EXTEND",
      "BOOKING_LATE_CHECKOUT",
      "BOOKING_REFUND",
      "BOOKING_EXPORT",
      "GUEST_VIEW",
      "GUEST_EDIT",
      "GUEST_EXPORT",
      "ENQUIRY_VIEW",
      "ENQUIRY_CREATE",
      "ENQUIRY_ASSIGN",
      "ENQUIRY_CONVERT",
      "ENQUIRY_DELETE",
      "ROOM_TYPE_VIEW",
      "ROOM_TYPE_EDIT",
      "ROOM_TYPE_PUBLISH",
      "ROOM_VIEW",
      "ROOM_EDIT",
      "ROOM_MAINTENANCE",
      "PRICING_VIEW",
      "PRICING_EDIT",
      "RATE_PLAN_EDIT",
      "OFFER_VIEW",
      "OFFER_EDIT",
      "OFFER_PUBLISH",
      "HOUSEKEEPING_VIEW",
      "HOUSEKEEPING_ASSIGN",
      "HOUSEKEEPING_UPDATE",
      "HOUSEKEEPING_CREATE_TASK",
      "REPORT_VIEW",
      "REPORT_EXPORT",
      "REVENUE_VIEW",
      "CMS_HERO_EDIT",
      "CMS_PAGE_EDIT",
      "CMS_GALLERY_EDIT",
      "CMS_GALLERY_UPLOAD",
      "CMS_REVIEW_EDIT",
      "CMS_ATTRACTION_EDIT",
      "CMS_AMENITY_EDIT",
      "SETTINGS_VIEW",
      "SETTINGS_EDIT",
      "AUDIT_LOG_VIEW",
      "NOTIFICATION_VIEW",
    ],
  },
  {
    key: "RECEPTION",
    name: "Reception",
    description: "Front-desk: bookings, guests, check-in/out.",
    isSystem: true,
    permissions: [
      "BOOKING_VIEW",
      "BOOKING_CREATE",
      "BOOKING_CREATE_WALKIN",
      "BOOKING_CREATE_PHONE",
      "BOOKING_MODIFY",
      "BOOKING_CHECKIN",
      "BOOKING_CHECKOUT",
      "BOOKING_ASSIGN_ROOM",
      "BOOKING_LATE_CHECKOUT",
      "GUEST_VIEW",
      "GUEST_EDIT",
      "ENQUIRY_VIEW",
      "ENQUIRY_CREATE",
      "ENQUIRY_ASSIGN",
      "ENQUIRY_CONVERT",
      "ROOM_TYPE_VIEW",
      "ROOM_VIEW",
      "HOUSEKEEPING_VIEW",
      "NOTIFICATION_VIEW",
    ],
  },
  {
    key: "MARKETING",
    name: "Marketing",
    description: "Website content, gallery, offers, reviews.",
    isSystem: true,
    permissions: [
      "CMS_HERO_EDIT",
      "CMS_PAGE_EDIT",
      "CMS_GALLERY_EDIT",
      "CMS_GALLERY_UPLOAD",
      "CMS_REVIEW_EDIT",
      "CMS_ATTRACTION_EDIT",
      "CMS_AMENITY_EDIT",
      "OFFER_VIEW",
      "OFFER_EDIT",
      "OFFER_PUBLISH",
      "PRICING_VIEW",
      "RATE_PLAN_EDIT",
      "REPORT_VIEW",
      "NOTIFICATION_VIEW",
    ],
  },
  {
    key: "HOUSEKEEPING",
    name: "Housekeeping",
    description: "Room status, tasks, maintenance.",
    isSystem: true,
    permissions: [
      "HOUSEKEEPING_VIEW",
      "HOUSEKEEPING_UPDATE",
      "HOUSEKEEPING_CREATE_TASK",
      "ROOM_VIEW",
      "ROOM_MAINTENANCE",
    ],
  },
];
